name: Build + test

on: [push]

strategy:
  matrix:
    compiler: [g++, clang++]
    target: [Release, Debug]

jobs:
  build-gcc-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Catch2
      run: ./ci/install_catch2.sh
    - name: Build + test
      shell: bash
      run: ./script/build.sh ${{ matrix.compiler }} ${{ matrix.target }}
