name: Make single header

on: [push]

jobs:
  make-single-header:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - name: Install Quom
      run: python3 -m pip install quom
    - name: Compile single header
      run: quom include/alex/alex.hpp single_include/alex/alex.hpp
    - name: Commit change
      run: |
        git pull
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Automatic single header update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        event-type: single-header-updated
        github_token: ${{ secrets.GITHUB_TOKEN }}
