name: Verify branch

on: [push]

jobs:
  verify-single-include:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-format
      run: sudo apt-get install clang-format
    - name: Install Quom
      run: python3 -m pip install quom
    - name: Verify
      shell: bash
      run: ./scripts/verify.sh
